# Site Build Settings

url:              https://giganttheo.github.io
baseurl:          ''

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Théo Gigant"
description:	       "PhD student working on multimodal summarization @ L2S"
author:              "Théo Gigant"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
